<h1>Sobre</h1>
<hr>



<div class="d-flex justify-content-center gap-3 flex-wrap">
    <?php foreach ($this->view->dados as $key => $info) { ?>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title"><?= $info['titulo'] ?></h5>
                <p class="card-text"><?= $info['descricao'] ?></p>
            </div>
        </div>
    <?php } ?>
</div>